# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: find-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  # kernel selection
  # select ONE of the following from-file line
  # or leave all three uncommented to use stock fedora kernel
  # ---
  #- from-file: modules-recipes/bazzite.yml 
  #- from-file: modules-recipes/cachy.yml  
  - from-file: modules-recipes/dnf.yml
  #- from-file: modules-recipes/flatpak.yml
  #- from-file: modules-recipes/codecs.yml

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          # you can override the title to make inclusion of both system and user repos clearer
          title: Flathub (user)
        install: # user flatpaks
          - com.valvesoftware.Steam
          - com.spotify.Client
          - com.heroicgameslauncher.hgl
          - com.discordapp.Discord
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - page.tesk.Refine
          - io.github.kolunmi.Bazaar

  # image-specific packages module
  # base/core packages are all handled by solarpowered-raw
  # and should not be added here.
  # systemd services related to image-specific packages
  # may also be placed within this module for simplicity
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
